### ISSUE TITLE
does not connect to the mqtt broker

### ISSUE THREAD

**Issue by rogerbl** [maads/tibber-pulse-live#1]
Hi! I'm running this java script in the PM2 environment and this is the log output. Seems like its not conecting to the mqtt broker:
35|app  | 2022-04-07T17:06:45.010Z- more than 1 minute since last update. exiting to try again.
35|app  | 2022-04-07T17:06:45.696Z- using default token
35|app  | 2022-04-07T17:06:45.763Z- connected to mqtt server: undefined
35|app  | 2022-04-07T17:06:46.075Z- pulse enabled
35|app  | Pulse is not enabled in this home.

my env.env file has these records:
TIBBER_MQTT=mqtt://192.168.100.129:1883
TIBBER_MQTT_TOPIC=ams
TIBBER_TOKEN=ca017be94edf30.............

But the script seems to ignore these settings, how come?

**Comment by maads** [comment]
This project was made to run in docker.  If you want to run only `app.js` you have to put the environment variables on the command line as the env.env file is not read. This file is an input parameter in the docker command.

Try running 

    TIBBER_MQTT=mqtt://192.168.100.129:1883 TIBBER_MQTT_TOPIC=ams TIBBER_TOKEN=476c477d8a039529478ebd690d35ddd80e3308ffc49b59c65b142321aee963a4 node app.js

**Comment by rogerbl** [comment]
Thanks, I did change  it so it Works now in PM2.
Actually I did only hardcode my token and homeId.
I find PM2 much more convenient to use than Docker.
Great work you did!

Regards Roger

Sendt fra E-post<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

Fra: Mads ***@***.***>
Sendt: fredag 8. april 2022 kl. 09.20
Til: ***@***.***>
Kopi: ***@***.***>; ***@***.***>
Emne: Re: [maads/tibber-pulse-live] does not connect to the mqtt broker (Issue #1)


This project was made to run in docker. If you want to run only app.js you have to put the environment variables on the command line as the env.env file is not read. This file is an input parameter in the docker command.

Try running

TIBBER_MQTT=mqtt://192.168.100.129:1883 TIBBER_MQTT_TOPIC=ams TIBBER_TOKEN=476c477d8a039529478ebd690d35ddd80e3308ffc49b59c65b142321aee963a4 node app.js
